name: epi-mqtt
version: V02.00-RC2
summary: EpiSensor MQTT broker for EpiSensor Edge gateways
description: |
  Provides MQTT messaging for EpiSensor Edge gateways. Based on
  Eclipse Mosquitto, enabling inter-snap communication and local
  MQTT connectivity for industrial IoT data transport.
icon: snap/gui/episensor.png
confinement: strict
grade: stable
base: core24

platforms:
  arm64:
  amd64:

slots:
  mqtt-config:
    interface: content
    content: mqtt-config
    write:
      - $SNAP_DATA/config
  mqtt-certs:
    interface: content
    content: mqtt-certs
    write:
      - $SNAP_DATA/certs

apps:
  mosquitto:
    command: launcher.sh
    daemon: simple
    restart-condition: always
    plugs: [home, network, network-bind]
  ctrl:
    command: usr/bin/mosquitto_ctrl
    plugs: [home, network]
  pub:
    command: usr/bin/mosquitto_pub
    plugs: [home, network]
  rr:
    command: usr/bin/mosquitto_rr
    plugs: [home, network]
  sub:
    command: usr/bin/mosquitto_sub
    plugs: [home, network]
  passwd:
    command: usr/bin/mosquitto_passwd
    plugs: [home]

parts:
  script:
    plugin: dump
    source: snap/local/
    prime:
      - default_config.conf
      - launcher.sh
  config:
    plugin: dump
    source: .
    prime:
      - mosquitto.conf

  mosquitto:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWITH_TESTS=OFF
      - -DWITH_WEBSOCKETS=OFF
      - -DWITH_PLUGIN_PERSIST_SQLITE=OFF
      - -DWITH_PLUGIN_EXAMPLES=OFF
    source: https://github.com/eclipse-mosquitto/mosquitto
    source-type: git
    source-tag: v2.1.2
    build-packages:
      - docbook-xsl
      - g++
      - gcc
      - libcjson-dev
      - libedit-dev
      - libssl-dev
      - xsltproc
    stage-packages:
      - ca-certificates
      - libcjson1
      - libssl3t64
    prime:
      - usr/sbin/mosquitto
      - usr/bin/mosquitto_ctrl
      - usr/bin/mosquitto_pub
      - usr/bin/mosquitto_rr
      - usr/bin/mosquitto_sub
      - usr/bin/mosquitto_passwd
      - usr/lib/*-linux-gnu/libcjson.so*
      - usr/lib/*-linux-gnu/libcrypto.so*
      - usr/lib/*-linux-gnu/libmosquitto.so*
      - usr/lib/*-linux-gnu/libmosquitto_common.so*
      - usr/lib/*-linux-gnu/libssl.so*
      - usr/lib/*-linux-gnu/mosquitto_acl_file.so*
      - usr/lib/*-linux-gnu/mosquitto_dynamic_security.so*
      - usr/lib/*-linux-gnu/mosquitto_password_file.so*
